# 데이터 불러오기

In [1]:
# 파이썬 경고 무시 설정
import warnings
warnings.filterwarnings('ignore')

In [2]:
# 필요한 라이브러리 임포트
import pandas as pd

# 파일 경로 설정
file_path='C:/Users/playdata2/work/Telco-Customer-Churn.csv'

# DataFrame 생성
df = pd.read_csv(file_path)

# 결과 확인
display(df)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# 데이터 전처리

In [3]:
# DataFrame -> 전용 함수 -> 기본 정보(행과 열) 제공(print) -> info() 함수
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
# 문제점: TotalCharges 컬럼 데이터 -> 공백과 같은 숫자로 변환할 수 없는 문자열(" ") 포함

## TotalCharges 컬럼의 값 -> 공백인 문자열(" ")인 행 인덱스 추출
space_index = df.query("TotalCharges == ' '").index   
print(space_index)

In [4]:
# 전처리 방법: TotalCharges 컬럼 -> 공백과 같이 숫자로 변환활 수 없는 문자열 포함인 행 제거

## 1단계: TotalCharges 컬럼의 자료형: 문자열 -> 숫자형으로 변환 ->pd.to_numeric(컬럼)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print("빈 문자열 처리 후 info 함수 적용")
df.info()

빈 문자열 처리 후 info 함수 적용
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [5]:
# 전처리 방법: TotalCharges 컬럼 -> 공백과 같이 숫자로 변환활 수 없는 문자열 포함인 행 제거

## 2단계: TotalCharges 컬럼 -> 누락인 행 제거 -> dropna()
df1 = df.dropna(ignore_index=True)
display(df1)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7028,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7029,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7030,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7031,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

# 데이터 탐색 및 EDA

In [6]:
# 필요한 모듈 임포트
import plotly.express as px

In [7]:
# 분석 목표: 정답 컬럼 -> 항목별 분포 -> 원 그래프 시각화

## 전체 고객 중 이탈자의 비율 파악 -> value_counts(normalize=True) -> reset_index()
df_churn_ratio = df1['Churn'].value_counts(normalize=True).reset_index()
display(df_churn_ratio)

print('-'*80)

## 시각화
fig1 = px.pie(
    data_frame=df_churn_ratio,
    names='Churn',
    values='proportion',
    title='고객 이탈 여부 비중',
    hole=0.3
)
fig1.show()

  Churn  proportion
0    No    0.734215
1   Yes    0.265785

--------------------------------------------------------------------------------

In [8]:
# 분석 목표: 계약 형태(Contract)와 고객 이탈의 관계 확인 -> 막대 그래프 시각화

## 계약 형태(Contract) 컬럼과 정답 컬럼 -> groupby의 기준 컬럼 + 행의 수 연산(size) -> reset_index()
df_contract_churn_count = df1.groupby(by=['Contract','Churn']).size().reset_index(name='Count') 
display(df_contract_churn_count)

print('-'*80)

fig2 = px.bar(
    data_frame=df_contract_churn_count,
    x='Contract',
    y='Count',
    color='Churn',
    barmode='group',
    text_auto='True',
    title='계약 형태별 고객 이탈 컬럼의 항목별 고객 수 비교'
)
fig2.show()

         Contract Churn  Count
0  Month-to-month    No   2220
1  Month-to-month   Yes   1655
2        One year    No   1306
3        One year   Yes    166
4        Two year    No   1637
5        Two year   Yes     48

--------------------------------------------------------------------------------

In [9]:
# 분석 목표: 가입 기간(tenure)과 고객 이탈의 관계 -> 히스토그램 시각화

## 시각화(x: tenure, color: Churn)
fig3 = px.histogram(
    data_frame=df1,
    x='tenure',
    color='Churn',
    barmode='group',
    title='가입 기간에 따른 이탈 분포'
)

## 모든 막대에 일괄적으로 검은색 경계선 넣기
fig3.update_traces(marker_line_color='black', marker_line_width=1)
fig3.show()

In [10]:
# 분석 목표: 월 요금(MonthlyCharges)과 고객 이탈의 관계 -> 히스토그램 시각화

## 시각화(x=MonthlyCharges, color=Churn)
fig4 = px.histogram(
    data_frame=df1,
    x='MonthlyCharges',
    color='Churn',
    barmode='group',
    title='월 사용 요금과 고객 이탈의 관계'
)

## 모든 막대에 일괄적으로 검은색 경계선 넣기
fig4.update_traces(marker_line_color='black', marker_line_width=1)
fig4.show()

In [11]:
# 분석 목표: 총 요금(TotalCharges)과 고객 이탈의 관계 -> 히스토그램

## 시각화(x: TotalCharges, color: Churn)
fig5 = px.histogram(
    data_frame=df1,
    x="TotalCharges",
    color="Churn",
    barmode="group",
    title="총 누적 요금과 고객 이탈의 관계"
)

## 모든 막대에 일괄적으로 검은색 경계선 넣기
fig5.update_traces(marker_line_color='black', marker_line_width=1)
fig5.show()

# Encoding

In [12]:
# 불필요한 컬럼 삭제
df2 = df1.drop(columns=['customerID'])
display(df2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7028,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7029,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7030,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7031,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [13]:
# 정답 컬럼(Churn) -> label 인코딩 ('No':0, 'Yes':1) -> map 함수
df2['Churn'] = df2['Churn'].map({'No':0, 'Yes':1})
display(df2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,0
7028,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0
7029,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0
7030,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,1
7031,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0

In [14]:
# feature -> 범주형 컬럼 -> One-Hot Encoding 적용

## 범주형 컬럼 추출 -> df.select_dtypes(include=[]) 
df_categorical = df2.select_dtypes(include=['object'])
display(df_categorical)

print('-'*80)

## 범주형 컬럼으로 구성된 DataFrame -> 컬럼 이름 추출 -> df.columns
categorical_cols = df_categorical.columns
print(f'범주형 컬럼의 이름: \n{categorical_cols}')

print('-'*80)

## 범주형 컬럼의 이름(Index 자료형) -> 리스트 자료형으로 변환 -> tolist()
categorical_cols_list = categorical_cols.tolist()
print(f'범주형 컬럼 이름의 리스트: \n{categorical_cols_list}')

# 보충: 1줄의 코드로 작성 -> df2.select_dtypes(include=['object']).columns.tolist()

print('-'*80)

## pd.get_dummies() 호출, 원-핫 인코딩 적용
df_onehot = pd.get_dummies(data=df2, columns=categorical_cols_list, dtype=int)

## 결과 확인
display(df_onehot)

,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,Female,Yes,No,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check
1,Male,No,No,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check
2,Male,No,No,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
3,Male,No,No,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic)
4,Female,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,Male,Yes,Yes,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check
7028,Female,Yes,Yes,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic)
7029,Female,Yes,Yes,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check
7030,Male,Yes,No,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check
7031,Male,No,No,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic)

--------------------------------------------------------------------------------
범주형 컬럼의 이름:
Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')
--------------------------------------------------------------------------------
범주형 컬럼 이름의 리스트:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']
--------------------------------------------------------------------------------

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,1,...,0,1,0,0,0,1,0,0,1,0
1,0,34,56.95,1889.50,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,1,1,0,1,...,0,1,0,0,0,1,0,0,0,1
3,0,45,42.30,1840.75,0,0,1,1,0,1,...,0,0,1,0,1,0,1,0,0,0
4,0,2,70.70,151.65,1,1,0,1,0,1,...,0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,24,84.80,1990.50,0,0,1,0,1,0,...,1,0,1,0,0,1,0,0,0,1
7028,0,72,103.20,7362.90,0,1,0,0,1,0,...,1,0,1,0,0,1,0,1,0,0
7029,0,11,29.60,346.45,0,1,0,0,1,0,...,0,1,0,0,0,1,0,0,1,0
7030,1,4,74.40,306.60,1,0,1,0,1,1,...,0,1,0,0,0,1,0,0,0,1
7031,0,66,105.65,6844.50,0,0,1,1,0,1,...,1,0,0,1,0,1,1,0,0,0

# 학습용 데이터와 평가용 데이터 생성

In [15]:
# X_data 생성 -> 정답 컬럼 제거
X_data = df_onehot.drop(columns=['Churn'])
display(X_data)

print('-'*80)

# y_data 생성 -> 정답 컬럼 인덱싱
y_data = df_onehot['Churn']
print(y_data)

print('-'*80)

# 정답의 항목별 비율 확인
ratio = y_data.value_counts(normalize=True)
print(f'정답 컬럼의 항목별 비율: \n{ratio}')

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,1,0,0,1,1,0,...,0,1,0,0,0,1,0,0,1,0
1,0,34,56.95,1889.50,0,1,1,0,1,0,...,0,0,1,0,1,0,0,0,0,1
2,0,2,53.85,108.15,0,1,1,0,1,0,...,0,1,0,0,0,1,0,0,0,1
3,0,45,42.30,1840.75,0,1,1,0,1,0,...,0,0,1,0,1,0,1,0,0,0
4,0,2,70.70,151.65,1,0,1,0,1,0,...,0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,24,84.80,1990.50,0,1,0,1,0,1,...,1,0,1,0,0,1,0,0,0,1
7028,0,72,103.20,7362.90,1,0,0,1,0,1,...,1,0,1,0,0,1,0,1,0,0
7029,0,11,29.60,346.45,1,0,0,1,0,1,...,0,1,0,0,0,1,0,0,1,0
7030,1,4,74.40,306.60,0,1,0,1,1,0,...,0,1,0,0,0,1,0,0,0,1
7031,0,66,105.65,6844.50,0,1,1,0,1,0,...,1,0,0,1,0,1,1,0,0,0

--------------------------------------------------------------------------------
0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64
--------------------------------------------------------------------------------
정답 컬럼의 항목별 비율:
Churn
0    0.734215
1    0.265785
Name: proportion, dtype: float64

In [16]:
# 80:20의 비율로 학습용과 평가용 데이터 생성

## 필요한 함수 임포트
from sklearn.model_selection import train_test_split

## train_test_split() 함수 호출 -> 무작위성 통제 -> random_state, stratify
X_train, X_test, y_train, y_test = train_test_split(
    X_data,
    y_data,
    test_size=0.2,
    random_state=0,
    stratify=y_data
)

In [17]:
# 학습용 데이터 확인 -> 행 인덱스
print(f'X_train의 행 인덱스: \n{X_train.index}')
print('-'*80)
print(f'y_train의 행 인덱스: \n{y_train.index}')

print('-'*80)

# 정답의 항목별 비율 확인
ratio_train = y_train.value_counts(normalize=True)
print(f'평가용 데이터의 정답의 항목별 비율: \n{ratio_train}')

X_train의 행 인덱스:
Index([3780, 1588, 2927,  198, 4504,  275, 5802, 6393,  355, 2595,
       ...
        963, 1206, 3431, 2125, 2163, 6168, 4543, 3956, 6130, 6814],
      dtype='int64', length=5625)
--------------------------------------------------------------------------------
y_train의 행 인덱스:
Index([3780, 1588, 2927,  198, 4504,  275, 5802, 6393,  355, 2595,
       ...
        963, 1206, 3431, 2125, 2163, 6168, 4543, 3956, 6130, 6814],
      dtype='int64', length=5625)
--------------------------------------------------------------------------------
평가용 데이터의 정답의 항목별 비율:
Churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64

# LogisticRegression(로지스틱 회귀) 모델

## 모델 생성

In [18]:
# 필요한 모델 클래스 임포트
from sklearn.linear_model import LogisticRegression

# 클래스 호출, 모델 생성
lr = LogisticRegression()

## 모델 학습: fit()

In [20]:
lr.fit(X_train, y_train)
print('학습 완료')

학습 완료

## 학습 완료 후 생성된 최적의 직선 확인: 기울기

In [ ]:
# 필요한 라이브러리 임포트
import numpy as np

# 기울기: model.coef_ -> 기울기(가중치)의 크기 추출
feature_importances = np.abs(lr.coef_[0])
print(f'각 컬럼별 직선의 기울기(가중치): \n{feature_importances}')

각 컬럼별 직선의 기울기(가중치):
[2.22597197e-01 6.63067125e-02 6.25303793e-04 3.93472416e-04
 1.85027372e-02 1.00579208e-01 4.54316796e-02 7.36502657e-02
 3.00539267e-02 1.49135872e-01 9.29564822e-02 2.12038427e-01
 2.18666668e-01 9.29564822e-02 6.62824020e-03 3.05335226e-01
 2.86261219e-01 1.00007938e-01 2.16123002e-01 1.00007938e-01
 2.35197009e-01 1.08689687e-01 1.00007938e-01 1.27763694e-01
 4.26294346e-02 1.00007938e-01 6.17034420e-02 2.45894242e-01
 1.00007938e-01 2.64968250e-01 8.61387098e-02 1.00007938e-01
 6.70647024e-02 7.75137399e-02 1.00007938e-01 5.84397325e-02
 4.42369612e-01 2.25782944e-01 3.35668613e-01 2.24405869e-01
 1.05323924e-01 1.17100002e-01 1.39757112e-01 2.93441346e-01
 1.55666178e-01]

In [28]:
# 기울기(가중치)의 크기와 컬럼 이름 -> DataFrame 생성

## 컬럼 이름(특성 이름)
feature_names = X_train.columns
print(f'특성(컬럼) 이름: \n{feature_names}')

print('-'*80)

## 컬럼 이름과 기울기(가중치)의 크기 -> dict 자료형 생성
dict_data = {
    'Feature': feature_names,
    'Importance': feature_importances
}

## DataFrame 생성 및 내림차순 정렬
df_lr_train_imp = pd.DataFrame(data=dict_data).sort_values(by='Importance', ascending=False)
display(df_lr_train_imp)

특성(컬럼) 이름:
Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')
--------------------------------------------------------------------------------

                                    Feature  Importance
36                  Contract_Month-to-month    0.442370
38                        Contract_Two year    0.335669
15                      InternetService_DSL    0.305335
43           PaymentMethod_Electronic check    0.293441
16              InternetService_Fiber optic    0.286261
29                          TechSupport_Yes    0.264968
27                           TechSupport_No    0.245894
20                       OnlineSecurity_Yes    0.235197
37                        Contract_One year    0.225783
39                      PaperlessBilling_No    0.224406
0                             SeniorCitizen    0.222597
12                         MultipleLines_No    0.218667
18                        OnlineSecurity_No    0.216123
11                         PhoneService_Yes    0.212038
44               PaymentMethod_Mailed check    0.155666
9                            Dependents_Yes    0.149136
42    PaymentMethod_Credit card (automatic)    0.139757
23                         OnlineBackup_Yes    0.127764
41  PaymentMethod_Bank transfer (automatic)    0.117100
21                          OnlineBackup_No    0.108690
40                     PaperlessBilling_Yes    0.105324
5                               gender_Male    0.100579
17                       InternetService_No    0.100008
31          StreamingTV_No internet service    0.100008
34      StreamingMovies_No internet service    0.100008
22         OnlineBackup_No internet service    0.100008
19       OnlineSecurity_No internet service    0.100008
25     DeviceProtection_No internet service    0.100008
28          TechSupport_No internet service    0.100008
13           MultipleLines_No phone service    0.092956
10                          PhoneService_No    0.092956
30                           StreamingTV_No    0.086139
33                       StreamingMovies_No    0.077514
7                               Partner_Yes    0.073650
32                          StreamingTV_Yes    0.067065
1                                    tenure    0.066307
26                     DeviceProtection_Yes    0.061703
35                      StreamingMovies_Yes    0.058440
6                                Partner_No    0.045432
24                      DeviceProtection_No    0.042629
8                             Dependents_No    0.030054
4                             gender_Female    0.018503
14                        MultipleLines_Yes    0.006628
2                            MonthlyCharges    0.000625
3                              TotalCharges    0.000393

## 학습용 데이터에 대한 특성의 중요도 시각화

In [30]:
# DataFrame -> 상위 5개 추출 -> df.head(5) 
df_lr_train_imp_top5 = df_lr_train_imp.head(5)
display(df_lr_train_imp_top5)

print('-'*80)

# 막대 그래프 -> top5 시각화 

## 필요한 모듈 임포트
import plotly.express as px

## 그래프 생성 출력
fig1 = px.bar(
    data_frame=df_lr_train_imp_top5,
    x='Feature',
    y='Importance',
    text_auto='.4f',
    title='[LogisticRegession] 학습용 데이터 특성 중요도 Top5'
)
fig1.show()

                           Feature  Importance
36         Contract_Month-to-month    0.442370
38               Contract_Two year    0.335669
15             InternetService_DSL    0.305335
43  PaymentMethod_Electronic check    0.293441
16     InternetService_Fiber optic    0.286261

--------------------------------------------------------------------------------

## 평가용 데이터를 이용한 예측: predict()

In [31]:
pred_test_lr = lr.predict(X_test)
print(pred_test_lr)

[1 0 0 ... 0 0 0]

## 모델 평가: accuracy_score() / classification_report()

In [25]:
# 필요한 함수 임포트
from sklearn.metrics import accuracy_score

# 평가용 데이터에 대한 성능 측정
acc_lr = accuracy_score(y_test, pred_test_lr)

# 결과 확인
print(f'LogisticRegression 모델의 정확도: {acc_lr:.4f}')

LogisticRegression 모델의 정확도: 0.8053

In [32]:
# 필요한 함수 임포트
from sklearn.metrics import classification_report

# 평가용 데이터에 대한 4가지 성능 측정
performance_lr = classification_report(y_test, pred_test_lr)

# 결과 확인
print(f'LogisticRegression 모델의 4가지 성능: \n{performance_lr}')

LogisticRegression 모델의 4가지 성능:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1033
           1       0.66      0.54      0.60       374

    accuracy                           0.81      1407
   macro avg       0.75      0.72      0.73      1407
weighted avg       0.80      0.81      0.80      1407

## LogisticRegression 분류 모델 고도화

### 탐색 도구 생성 및 탐색 실행

In [38]:
# 필요한 클래스 임포트
from sklearn.linear_model import LogisticRegression 
from sklearn.model_selection import GridSearchCV

# 성능 고도화 대상 모델 생성
lr = LogisticRegression(random_state=0)

# 최적화 할 매개 변수와 탐색의 조건 설정 -> 5*4=20가지
params = {
    'C': [0.01, 0.1, 1, 10, 100],
    'max_iter': [100, 500, 1000, 5000]
}

# 탐색 도구 생성
grid_lr = GridSearchCV(
    estimator=lr,
    param_grid=params,
    scoring='f1',
    cv=5
)

# 학습 및 검증
grid_lr.fit(X_train, y_train)
print("검증 완료")

검증 완료

In [39]:
# best 모델 추출
best_lr = grid_lr.best_estimator_
print(best_lr)

LogisticRegression(C=100, max_iter=500, random_state=0)

In [40]:
# 검증용에 대한 최적의 성능 확인
print(grid_lr.best_score_)

0.5986961307318313

#### best 조건을 이용하여 모델 생성

In [44]:
# C=1(기본값), max_iter=500 조건으로 모델 생성
best_lr1 = LogisticRegression(max_iter=500,random_state=0)
print(best_lr1)

LogisticRegression(max_iter=500, random_state=0)

#### 모델 학습

In [46]:
best_lr1.fit(X_train, y_train)
print("학습 완료")

학습 완료

### 학습용 데이터에 대한 특성의 중요도 시각화

In [51]:
# best 모델: 생성된 최적의 직선 기울기의 크기 확인
best_lr1_train_importances = np.abs(best_lr1.coef_[0])
print(best_lr1_train_importances)

[2.11636028e-01 6.31196533e-02 4.49196531e-04 3.72953981e-04
 2.74073061e-02 1.08076628e-01 4.74715354e-02 8.80123990e-02
 4.35606590e-03 1.39840000e-01 9.17233633e-02 2.27207298e-01
 2.21383486e-01 9.17233633e-02 5.82381204e-03 3.27925816e-01
 3.07095427e-01 1.14653546e-01 1.90456305e-01 1.14653546e-01
 2.11286693e-01 1.01812660e-01 1.14653546e-01 1.22643048e-01
 3.18640436e-02 1.14653546e-01 5.26944320e-02 2.06854362e-01
 1.14653546e-01 2.27684751e-01 9.15010129e-02 1.14653546e-01
 7.06706245e-02 8.64178912e-02 1.14653546e-01 6.55875028e-02
 5.91749045e-01 1.24979436e-01 6.02253543e-01 2.28166374e-01
 9.26824396e-02 1.22412804e-01 1.43389838e-01 2.61745332e-01
 1.31426624e-01]

In [52]:
# 기울기(가중치)의 크기와 컬럼 이름 -> DataFrame 생성

## 컬럼 이름(특성 이름)
feature_names = X_train.columns
print(f'특성(컬럼) 이름: \n{feature_names}')

print('-'*80)

## 컬럼 이름과 기울기(가중치)의 크기 -> dict 자료형 생성
dict_data = {
    'Feature': feature_names,
    'Importance': best_lr1_train_importances
}

## DataFrame 생성 및 내림차순 정렬
df_best_lr_train_imp = pd.DataFrame(data=dict_data).sort_values(by='Importance', ascending=False)
display(df_best_lr_train_imp)

특성(컬럼) 이름:
Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges',
       'gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')
--------------------------------------------------------------------------------

                                    Feature  Importance
38                        Contract_Two year    0.602254
36                  Contract_Month-to-month    0.591749
15                      InternetService_DSL    0.327926
16              InternetService_Fiber optic    0.307095
43           PaymentMethod_Electronic check    0.261745
39                      PaperlessBilling_No    0.228166
29                          TechSupport_Yes    0.227685
11                         PhoneService_Yes    0.227207
12                         MultipleLines_No    0.221383
0                             SeniorCitizen    0.211636
20                       OnlineSecurity_Yes    0.211287
27                           TechSupport_No    0.206854
18                        OnlineSecurity_No    0.190456
42    PaymentMethod_Credit card (automatic)    0.143390
9                            Dependents_Yes    0.139840
44               PaymentMethod_Mailed check    0.131427
37                        Contract_One year    0.124979
23                         OnlineBackup_Yes    0.122643
41  PaymentMethod_Bank transfer (automatic)    0.122413
19       OnlineSecurity_No internet service    0.114654
17                       InternetService_No    0.114654
22         OnlineBackup_No internet service    0.114654
34      StreamingMovies_No internet service    0.114654
31          StreamingTV_No internet service    0.114654
28          TechSupport_No internet service    0.114654
25     DeviceProtection_No internet service    0.114654
5                               gender_Male    0.108077
21                          OnlineBackup_No    0.101813
40                     PaperlessBilling_Yes    0.092682
13           MultipleLines_No phone service    0.091723
10                          PhoneService_No    0.091723
30                           StreamingTV_No    0.091501
7                               Partner_Yes    0.088012
33                       StreamingMovies_No    0.086418
32                          StreamingTV_Yes    0.070671
35                      StreamingMovies_Yes    0.065588
1                                    tenure    0.063120
26                     DeviceProtection_Yes    0.052694
6                                Partner_No    0.047472
24                      DeviceProtection_No    0.031864
4                             gender_Female    0.027407
14                        MultipleLines_Yes    0.005824
8                             Dependents_No    0.004356
2                            MonthlyCharges    0.000449
3                              TotalCharges    0.000373

In [53]:
# DataFrame -> 상위 5개 추출 -> df.head(5) 
df_best_lr_train_imp_top5 = df_best_lr_train_imp.head(5)
display(df_best_lr_train_imp_top5)

print('-'*80)

# 막대 그래프 -> top5 시각화 

## 필요한 모듈 임포트
import plotly.express as px

## 그래프 생성 출력
fig2 = px.bar(
    data_frame=df_best_lr_train_imp_top5,
    x='Feature',
    y='Importance',
    text_auto='.4f',
    title='[LogisticRegession] 학습용 데이터 특성 중요도 Top5'
)
fig2.show()

                           Feature  Importance
38               Contract_Two year    0.602254
36         Contract_Month-to-month    0.591749
15             InternetService_DSL    0.327926
16     InternetService_Fiber optic    0.307095
43  PaymentMethod_Electronic check    0.261745

--------------------------------------------------------------------------------

### 평가용 데이터를 이용한 예측

In [41]:
pred_test_best_lr = best_lr.predict(X_test)
print(pred_test_best_lr)

[1 0 0 ... 0 0 0]

In [47]:
# 새로운 조건으로 학습시킨 모델
pred_test_best_lr1 = best_lr1.predict(X_test)
print(pred_test_best_lr1)

[1 0 0 ... 0 0 0]

### 모델 평가

In [42]:
# 필요한 함수 임포트
from sklearn.metrics import classification_report

# 평가용 데이터에 대한 4가지 성능 측정
performace_best_lr = classification_report(y_test, pred_test_best_lr)

# 결과 확인
print(f'고도화된 LogisticReression 모델의 평가용 데이터에 대한 4가지 성능: \n{performace_best_lr}')

고도화된 LogisticReression 모델의 평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

           0       0.85      0.90      0.87      1033
           1       0.66      0.55      0.60       374

    accuracy                           0.80      1407
   macro avg       0.75      0.72      0.73      1407
weighted avg       0.80      0.80      0.80      1407

In [48]:
# 필요한 함수 임포트
from sklearn.metrics import classification_report

# 평가용 데이터에 대한 4가지 성능 측정(새로 학습한 모델)
performace_best_lr1 = classification_report(y_test, pred_test_best_lr1)

# 결과 확인
print(f'고도화된 LogisticReression 모델의 평가용 데이터에 대한 4가지 성능: \n{performace_best_lr1}')

고도화된 LogisticReression 모델의 평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

           0       0.85      0.90      0.87      1033
           1       0.67      0.55      0.60       374

    accuracy                           0.81      1407
   macro avg       0.76      0.73      0.74      1407
weighted avg       0.80      0.81      0.80      1407

# SVM 분류 모델

## 모델 생성

In [ ]:
# 필요한 모델 클래스 임포트
from sklearn.svm import SVC

# 클래스 호출, 모델 생성
svc = SVC()

## 모델 학습: fit()

In [ ]:
svc.fit(X_train, y_train)
print('학습 완료')

## 평가용 데이터를 이용한 예측: predict()

In [ ]:
pred_test_svc = svc.predict(X_test)
print(pred_test_svc)

## 모델 평가: accuracy_score()

In [ ]:
# 필요한 함수 임포트
from sklearn.metrics import accuracy_score

# 평가용에 데이터에 대한 성능 측정
acc_svc = accuracy_score(y_test, pred_test_svc)

# 결과 확인
print(f'SVM 분류 모델의 정확도: {acc_svc:.4f}')

# DecisionTree 분류 모델

## 모델 생성

In [ ]:
# 필요한 모델 클래스 임포트
from sklearn.tree import DecisionTreeClassifier

# 클래스 호출, 모델 생성
dt = DecisionTreeClassifier(random_state=0)

## 모델 학습: fit()

In [ ]:
dt.fit(X_train, y_train)
print('학습 완료')

## 평가용 데이터를 이용한 예측: predict()

In [ ]:
pred_test_dt = dt.predict(X_test)
print(pred_test_dt)

## 모델 평가: accuracy_score()

In [ ]:
# 필요한 함수 임포트
from sklearn.metrics import accuracy_score

# 평가용 데이터에 대한 성능 측정
acc_dt = accuracy_score(y_test, pred_test_dt)

# 결과 확인
print(f'DecisionTree 분류 모델의 정확도: {acc_dt:.4f}')