# 데이터 불러오기

In [62]:
# 파이썬 경고 무시 설정
import warnings
warnings.filterwarnings('ignore')

In [63]:
# 필요한 라이브러리 임포트
import pandas as pd

# 파일 경로 설정
file_path=r'./Telco-Customer-Churn.csv'

# DataFrame 생성
df = pd.read_csv(file_path)

# 결과 확인
display(df)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

# 데이터 전처리

In [64]:
# DataFrame -> 전용 함수 -> 기본 정보(행과 열) 제공(print) -> info() 함수
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [65]:
# 문제점: TotalCharges 컬럼 데이터 -> 공백과 같은 숫자로 변환할 수 없는 문자열(" ") 포함

## TotalCharges 컬럼의 값 -> 공백인 문자열(" ")인 행 인덱스 추출
space_index = df.query("TotalCharges == ' '").index   
print(space_index)

Index([488, 753, 936, 1082, 1340, 3331, 3826, 4380, 5218, 6670, 6754], dtype='int64')

In [66]:
# 전처리 방법: TotalCharges 컬럼 -> 공백과 같이 숫자로 변환활 수 없는 문자열 포함인 행 제거

## 1단계: TotalCharges 컬럼의 자료형: 문자열 -> 숫자형으로 변환 ->pd.to_numeric(컬럼)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
print("빈 문자열 처리 후 info 함수 적용")
df.info()

빈 문자열 처리 후 info 함수 적용
<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.8 MB

In [67]:
# 전처리 방법: TotalCharges 컬럼 -> 공백과 같이 숫자로 변환활 수 없는 문자열 포함인 행 제거

## 2단계: TotalCharges 컬럼 -> 누락인 행 제거 -> dropna()
df1 = df.dropna(ignore_index=True)
display(df1)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7028,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7029,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7030,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7031,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

# 데이터 탐색 및 EDA

In [68]:
# 필요한 모듈 임포트
import plotly.express as px

In [69]:
# 분석 목표: 정답 컬럼 -> 항목별 분포 -> 원 그래프 시각화

## 전체 고객 중 이탈자의 비율 파악 -> value_counts(normalize=True) -> reset_index()
df_churn_ratio = df1['Churn'].value_counts(normalize=True).reset_index()
display(df_churn_ratio)

  Churn  proportion
0    No    0.734215
1   Yes    0.265785

In [70]:
'''
fig2 = px.bar(
    df_churn_ratio,
    #x='contract',
    y='Count',
    color='Churn',
    text_auto=True,
    title='제목'
)
'''

# 분석 목표: 가입 기간(tenure)과 고객 이탈의 관계 -> 히스토그램 시각화
## 시각화 (x: ternure,color:Churn)
fig3 = px.histogram(
    data_frame= df1,
    x='tenure',
    color='Churn',
    barmode='group',
    title='가입 기간에 따른 이탈 분포'
)


fig3.update_traces(
    marker_line_color='black',marker_line_width=1
)
fig3.show()

In [71]:
# 분석 목표: 월 요금(M.Class)과 고객 이탈의 관계 히스토그램 시각화
## 시각화(M.Class,color='Churn')

fig4 = px.histogram(
    data_frame=df1,
    x='MonthlyCharges',
    color='Churn',
    barmode='group'
)

fig4.update_traces(
    marker_line_color='black',marker_line_width=1
)
fig4.show()

In [72]:
# 분석 목표: 총 요금(total.charges)과 고객 이탈의 관계 -> 히스토그램 시각화
# 시각화 
# 다중공선성: 
# 똑같은 데이터 가 있을경우 불필요하고 지워야 하는 불필요한 작업도 하게 된다.
fig5 = px.histogram(
    df1,
    x='TotalCharges',
    color='Churn',
    barmode='group',
    title="총 누적과 요금과 고객 이탈의 관계"
)

fig5.update_traces(marker_line_color='black',marker_line_width=1)

One-Hot-Encoding

In [73]:
# 고유 번호 삭제
df2 = df1.drop(columns='customerID')
# 출력!
#display(df2)

#replace(str) == map(int) 
df2['Churn'] = df2['Churn'].map({'No':0,'Yes':1})
display(df2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,0
7028,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,0
7029,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0
7030,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,1
7031,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,0

## 특정 범주형 컬럼 만 (원핫 인코딩 적용)
## 범주형 컴럼 추출 -> df.select_dtype(include=[])->리스트 자료형으로 변환

In [74]:
df_categorical = df2.select_dtypes(include=[str])
#display(df_categorical)

# select_dtypes() ,매개변수 include=[타입 만 묶음]
#df_categorical.info()

#"ALL columns output!""
cols = df_categorical.columns

#출력!
#print("ALL columns:\n",cols)
#df2.info()

#리스트 로 형변환 tolist()
colos_to_list = cols.tolist()
#print("형변환 to list:\n",colos_to_list)

#범주형,원-핫(인코딩)
#teste = df2.select_dtypes(include=[str]).columns.tolist()
#print(teste)

#float64 2개 있다.
#int64 타입으로 구별해야될것 같다. 하지만 모르겠다.
#문자열
df_onehost = pd.get_dummies(df2,columns=colos_to_list,dtype=int)
#df_onehost.info()
display(df_onehost)
#print("one hot:",)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,1,...,0,1,0,0,0,1,0,0,1,0
1,0,34,56.95,1889.50,0,0,1,1,0,1,...,0,0,1,0,1,0,0,0,0,1
2,0,2,53.85,108.15,1,0,1,1,0,1,...,0,1,0,0,0,1,0,0,0,1
3,0,45,42.30,1840.75,0,0,1,1,0,1,...,0,0,1,0,1,0,1,0,0,0
4,0,2,70.70,151.65,1,1,0,1,0,1,...,0,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,24,84.80,1990.50,0,0,1,0,1,0,...,1,0,1,0,0,1,0,0,0,1
7028,0,72,103.20,7362.90,0,1,0,0,1,0,...,1,0,1,0,0,1,0,1,0,0
7029,0,11,29.60,346.45,0,1,0,0,1,0,...,0,1,0,0,0,1,0,0,1,0
7030,1,4,74.40,306.60,1,0,1,0,1,1,...,0,1,0,0,0,1,0,0,0,1
7031,0,66,105.65,6844.50,0,0,1,1,0,1,...,1,0,0,1,0,1,1,0,0,0

# 학습용 데이터와 평가용 생성

In [75]:
X_data = df_onehost.drop(columns=['Churn'])
print("="*50)
y_data = df_onehost['Churn']

#새로운 데이터프레임에 "정규화" 진행!
ratio = y_data.value_counts(normalize=True)
print("정답 데이터 생성!")

==================================================
정답 데이터 생성!

In [76]:
## 학습용:평가용(8:2 비율)
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X_data,
    y_data,
    test_size=0.2,
    random_state=0,
    stratify=y_data
)

# 학습용 데이터 확인 -> 행 인덱스
print(X_train.index)
print(y_train.index)
print("="*50)
#############################
#빈도수 연산!
ratio_train = y_train.value_counts(normalize=True)
print(ratio_train)
print("="*50)

Index([3780, 1588, 2927,  198, 4504,  275, 5802, 6393,  355, 2595,
       ...
        963, 1206, 3431, 2125, 2163, 6168, 4543, 3956, 6130, 6814],
      dtype='int64', length=5625)
Index([3780, 1588, 2927,  198, 4504,  275, 5802, 6393,  355, 2595,
       ...
        963, 1206, 3431, 2125, 2163, 6168, 4543, 3956, 6130, 6814],
      dtype='int64', length=5625)
==================================================
Churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64
==================================================

## 분류 (로지스틱 회귀)

In [82]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
## 모델 생성
lr =  LogisticRegression()

## 모델 학습
lr.fit(X_train,y_train)
print("학습 완료!")

## 모델 예측
pred_test_lr = lr.predict(X_test)

## 모델 평가
acc_lr = accuracy_score(y_test, pred_test_lr)
print(acc_lr)

학습 완료!
0.8052594171997157

In [90]:
#다중 모델
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#모델 생성
svc = SVC()

#표준화가 아닌가? 아니다 표준화를 한다!
scaler = StandardScaler()
#X_train_scaled = scaler.fit_transform(X_train)

#모델 학습
svc.fit(X_train,y_train)
print("학습 완료!")

#모델 예측
pred_test = svc.predict(X_test) 
#print(pred_test)

#모델 평가
acc_svc = accuracy_score(y_test,pred_test)
print(acc_svc)
print("="*50)

학습 완료!
0.7341862117981521
==================================================

트리 분류 모델

In [96]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

#모델 생성
dt = DecisionTreeClassifier(random_state=0)

#모델 학습
dt.fit(X_train,y_train)
print("학습 완료!")

#모델 예측
predict_dt = dt.predict(X_test)

#모델 평가
acc_dt = accuracy_score(y_test,predict_dt)
print(f"모델 성능:{acc_dt}")

학습 완료!
모델 성능:0.7192608386638237

# 회귀
선형 회귀
다선형 회귀
SVC (양쪽)
트리 (양쪽)
# 분류
SVM (양쪽)
트리 (양쪽)

랜덤 포레스트
앙상블: Bagging, Boosting,Stacking