# 당뇨병 건강 지표 데이터 분석

## 데이터 불러오기

In [1]:
# 필요한 라이브러리 임포트
import pandas as pd

# 파일 경로 설정
file_path='C:/Users/playdata2/work/diabetes_binary_5050split_health_indicators_BRFSS2015.csv'

# DataFrame 생성
df = pd.read_csv(file_path)

# 결과 확인
display(df)

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,0.0,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,0.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,1.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
70688,1.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
70689,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
70690,1.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
70691,1.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

## 학습용과 평가용 데이터 생성

In [2]:
# 전체 데이터 -> 학습용 : 평가용 = 80 : 20으로 분할

## 필요한 함수 임포트
from sklearn.model_selection import train_test_split

## X_data 생성 -> 정답 컬럼 제거
X_data = df.drop(columns=['Diabetes_binary'])
display(X_data)

print('-'*80)

## y_data 생성 -> 정답 인덱싱
y_data = df['Diabetes_binary']
print(y_data)

print('-'*80)

## train_test_split() 함수 호출 -> 무작위성 통제 -> random_state, stratify 적용
X_train, X_test, y_train, y_test = train_test_split(
    X_data,
    y_data,
    test_size=0.2,
    random_state=0,
    stratify=y_data
)

,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,1.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,3.0,5.0,30.0,0.0,1.0,4.0,6.0,8.0
1,1.0,1.0,1.0,26.0,1.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,12.0,6.0,8.0
2,0.0,0.0,1.0,26.0,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,10.0,0.0,1.0,13.0,6.0,8.0
3,1.0,1.0,1.0,28.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,3.0,0.0,3.0,0.0,1.0,11.0,6.0,8.0
4,0.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70687,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
70688,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
70689,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
70690,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
70691,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

--------------------------------------------------------------------------------
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
70687    1.0
70688    1.0
70689    1.0
70690    1.0
70691    1.0
Name: Diabetes_binary, Length: 70692, dtype: float64
--------------------------------------------------------------------------------

In [4]:
# 학습용 데이터 확인 -> 인덱스 확인

## X_train 확인
print(f'X_train 행 인덱스: \n{X_train.index}')

print('-'*80)

## y_train 확인
print(f'y_train 행 인덱스: \n{y_train.index}')

X_train 행 인덱스:
Index([35369, 40967, 27238, 50582, 38854, 49562, 23991, 13093, 25789, 45889,
       ...
       23615,  6543, 38363, 45899, 65393, 22335,  7166, 66883, 36604, 27209],
      dtype='int64', length=56553)
--------------------------------------------------------------------------------
y_train 행 인덱스:
Index([35369, 40967, 27238, 50582, 38854, 49562, 23991, 13093, 25789, 45889,
       ...
       23615,  6543, 38363, 45899, 65393, 22335,  7166, 66883, 36604, 27209],
      dtype='int64', length=56553)

## DecisionTree 분류 모델 고도화

### GridSearchCV 탐색 도구를 이용한 고도화

#### 탐색 도구 생성 및 탐색 실행

In [36]:
# 필요한 클래스 임포트
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# 성능 고도화 대상 모델 생성
dt = DecisionTreeClassifier(random_state=0)

# 최적화 할 매개 변수와 탐색의 조건 설정 -> key:value -> dict 자료형
params = {
    'max_depth': [3,4,5,6,7,8,9,10],
    'min_samples_leaf': [2,3,4,5]
}

# GridSearchCV 탐색 도구 호출, 도구 생성
grid_dt = GridSearchCV(
    estimator=dt,
    param_grid=params,
    scoring='accuracy',
    cv=5
)

# 탐색 도구 학습 및 검증
grid_dt.fit(X_train, y_train)
print("탐색 완료")

탐색 완료

In [37]:
# best 모델 추출
best_dt = grid_dt.best_estimator_
print(best_dt)

DecisionTreeClassifier(max_depth=7, min_samples_leaf=5, random_state=0)

In [38]:
# 검증용에 대한 최적의 성능 확인
print(grid_dt.best_score_)

0.7418526772331278

#### 평가용 데이터를 이용한 예측

In [39]:
pred_test_dt = best_dt.predict(X_test)
print(pred_test_dt)

[1. 0. 1. ... 1. 0. 1.]

#### 모델 평가

In [11]:
# 필요한 함수 임포트
from sklearn.metrics import accuracy_score

# 평가용 데이터에 대한 성능 측정
acc_dt = accuracy_score(y_test, pred_test_dt)

# 결과 확인
print(f'고도화된 DecisionTree 분류 모델의 평가용 데이터 대한 성능: {acc_dt:.4f}')

고도화된 DecisionTree 분류 모델의 평가용 데이터 대한 성능: 0.7411

In [40]:
# 평가 지표 변경: accuracy_score -> classification_report로 변견

## 필요한 함수 임포트
from sklearn.metrics import classification_report

## 평가용 데이터에 대한 4가지 성능 측정
performance_dt = classification_report(y_test, pred_test_dt) 

## 결과 확인
print(f"고도화된 DecisionTree 분류 모델의 평가용 데이터에 대한 4가지 성능: \n{performance_dt}")

고도화된 DecisionTree 분류 모델의 평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

         0.0       0.75      0.73      0.74      7070
         1.0       0.73      0.75      0.74      7069

    accuracy                           0.74     14139
   macro avg       0.74      0.74      0.74     14139
weighted avg       0.74      0.74      0.74     14139

## RandomForest 분류 모델 고도화

### 탐색 도구 생성 및 탐색 실행

In [10]:
# 필요한 클래스 임포트
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# 성능 고도화 대상 모델 생성
rf = RandomForestClassifier(random_state=0)

# 최적화 할 매개 변수와 탐색 조건 설정
params = {
    'n_estimators':[100, 200, 300, 400],
    'max_depth':[5,6,7,8,9],
    'min_samples_leaf':[2,3,4,5]
}

# 탐색 도구 생성
grid_rf = GridSearchCV(
    estimator=rf,
    param_grid=params,
    scoring='accuracy',
    cv=5
)

# 탐색 도구 학습 및 검증
grid_rf.fit(X_train, y_train)
print("탐색 완료")

탐색 완료

In [11]:
# best 모델 추출
best_rf = grid_rf.best_estimator_
print(best_rf)

RandomForestClassifier(max_depth=9, min_samples_leaf=2, n_estimators=400,
                       random_state=0)

In [13]:
# 검증용 데이터에 대한 최적의 성능
print(grid_rf.best_score_)

0.7510829461801813

### 평가용 데이터를 이용한 예측

In [14]:
pred_test_rf = best_rf.predict(X_test)

### 모델 평가

In [15]:
# 필요한 함수 임포트
from sklearn.metrics import accuracy_score

# 평가용 데이터에 대한 성능 측정
acc_rf = accuracy_score(y_test, pred_test_rf)

# 결과 확인
print(f'고도화된 RandomForest 분류 모델의 평가용 데이터 대한 성능: {acc_rf:.4f}')

고도화된 RandomForest 분류 모델의 평가용 데이터 대한 성능: 0.7519

In [27]:
## 평가 기준 변경: accuracy_score -> classification_report

## 필요한 함수 임포트
from sklearn.metrics import classification_report

## 평가용 데이터에 대한 4가지 성능 측정
performance_rf = classification_report(y_test, pred_test_rf)

## 결과 확인
print(f'고도화된 RandomForest 분류 모델의 평가용 데이터에 대한 4가지 성능: \n{performance_rf}')

고도화된 RandomForest 분류 모델의 평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

         0.0       0.77      0.72      0.74      7070
         1.0       0.74      0.78      0.76      7069

    accuracy                           0.75     14139
   macro avg       0.75      0.75      0.75     14139
weighted avg       0.75      0.75      0.75     14139

## RandomizedSearchCV 탐색 도구를 이용한 RandomForest 분류 모델 고도화

### 탐색 도구 생성 및 탐색 실행

In [51]:
# 필요한 클래스 임포트
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV

# 성능 고도화 대상 모델 생성
rf = RandomForestClassifier(random_state=0)

# 최적화 할 매개 변수와 탐색 조건 설정
params = {
    'n_estimators':[100,200,300,400,500,600,700,800,900,1000],
    'max_depth':[5,6,7,8,9,10],
    'min_samples_leaf':[2,3,4,5]
}

# 탐색 도구 생성
random_rf = RandomizedSearchCV(
    estimator=rf,
    param_distributions=params,
    # 전체 탐색 조건 240가지 -> 30가지 -> 무작위로 추출해서 탐색할 횟수
    n_iter=30,
    scoring='f1',
    cv=5,
    random_state=0
)

# 탐색 도구 학습 및 검증
random_rf.fit(X_train, y_train)
print("검증 완료")

검증 완료

In [52]:
# best 모델 추출
best_rf_random = random_rf.best_estimator_
print(best_rf_random)

RandomForestClassifier(max_depth=10, min_samples_leaf=4, n_estimators=800,
                       random_state=0)

In [53]:
# 검증용 데이터에 대한 최적의 성능 확인
print(random_rf.best_score_)

0.7616638179230998

### 평가용 데이터를 이용한 예측

In [54]:
pred_test_rf_random = best_rf_random.predict(X_test)

### 모델 평가

In [55]:
# 필요한 함수 임포트
from sklearn.metrics import classification_report

# 평가용 데이터에 대한 4가지 성능 측정
performance_rf_random = classification_report(y_test, pred_test_rf_random)

# 결과 확인
print(f'평가용 데이터에 대한 4가지 성능: \n{performance_rf_random}')

평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

         0.0       0.77      0.72      0.74      7070
         1.0       0.74      0.79      0.76      7069

    accuracy                           0.75     14139
   macro avg       0.75      0.75      0.75     14139
weighted avg       0.75      0.75      0.75     14139

### best 모델 저장

In [ ]:
# 필요한 라이브러리 임포트
import joblib

# best 모델 저장
joblib.dump(best_rf_random, 'best_rf_random.pkl')

['best_rf_random.pkl']

### best 모델 불러오기 및 성능 측정

In [59]:
# best 모델 불러오기
loaded_best_rf_random = joblib.load('C:/Users/playdata2/work/best_rf_random.pkl')
print(loaded_best_rf_random)

RandomForestClassifier(max_depth=10, min_samples_leaf=4, n_estimators=800,
                       random_state=0)

In [58]:
# best 모델을 이용한 성능 측정

## 평가용 데이터를 이용한 예측
pred_test_rf_random_loaded = loaded_best_rf_random.predict(X_test)

## 평가용 데이터를 이용한 성능 평가
performance_rf_random_loaded = classification_report(y_test, pred_test_rf_random_loaded)

# 결과 확인
print(f'불러온 모델을 이용한 평가용 데이터에 대한 4가지 성능: \n{performance_rf_random_loaded}')

불러온 모델을 이용한 평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

         0.0       0.77      0.72      0.74      7070
         1.0       0.74      0.79      0.76      7069

    accuracy                           0.75     14139
   macro avg       0.75      0.75      0.75     14139
weighted avg       0.75      0.75      0.75     14139

## XGBoost 분류 모델 고도화

### 탐색 도구 생성 및 탐색 실행

In [16]:
# 필요한 클래스 임포트
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

# 성능 고도화 대상 모델 생성
xgb = XGBClassifier(random_state=0)

# 최적화 할 매개 변수와 탐색 범위 설정
params = {
    'n_estimators': [50, 100, 200, 300],
    'learning_rate': [0.05,0.1,0.5],
    'max_depth': [3,4,5],
    'min_samples_leaf': [2,3,4,5]
}

# 탐색 도구 생성
grid_xgb = GridSearchCV(
    estimator=xgb,
    param_grid=params,
    scoring='accuracy',
    cv=5
)

# 탐색 도구 학습 및 검증
grid_xgb.fit(X_train, y_train)
print("검증 완료")

검증 완료

In [17]:
# best 모델 추출
best_xgb = grid_xgb.best_estimator_
print(best_xgb)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, min_samples_leaf=2,
              missing=nan, monotone_constraints=None, multi_strategy=None,
              n_estimators=200, n_jobs=None, ...)

In [18]:
# 검증용 데이터에 대한 최적의 성능 확인
print(grid_xgb.best_score_)

0.7536822906052738

### 평가용 데이터를 이용한 예측

In [28]:
pred_test_xgb = best_xgb.predict(X_test)

### 모델 평가

In [29]:
# 필요한 함수 임포트
from sklearn.metrics import classification_report

# 평가용 데이터에 대한 4가지 성능 측정
performance_xgb = classification_report(y_test, pred_test_xgb)

# 결과 확인
print(f'고도화된 XGBoost 분류 모델의 평가용 데이터에 대한 4가지 성능: \n{performance_xgb}')

고도화된 XGBoost 분류 모델의 평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

         0.0       0.77      0.72      0.75      7070
         1.0       0.74      0.79      0.76      7069

    accuracy                           0.75     14139
   macro avg       0.76      0.75      0.75     14139
weighted avg       0.76      0.75      0.75     14139

## Stacking 분류 모델

### 1단계: 개별 기본 모델 생성

In [41]:
# 필요한 클래스 임포트
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [42]:
# 앞에서 고도화를 완료한 개별 모델을 Stacking의 기본 모델로 지정
base_models = [
    ('dt', best_dt),
    ('rf', best_rf),
    ('xgb', best_xgb)
]

### 2단계: 최종 메타 모델 생성

In [43]:
# 필요한 클래스 임포트
from sklearn.linear_model import LogisticRegression

# 1단계 모델들의 예측값을 받아 최종 판단을 내리는 모델 생성
final_meta = LogisticRegression(max_iter=1000)

### Stacking 모델 생성

In [45]:
# 필요한 클래스 임포트
from sklearn.ensemble import StackingClassifier

# base_models, final_meta 결합
stack = StackingClassifier(
    estimators=base_models,
    final_estimator=final_meta
)

### 모델 학습

In [47]:
stack.fit(X_train, y_train)
print("학습 완료")

학습 완료

### 평가용 데이터에 대한 예측

In [48]:
pred_test_stack = stack.predict(X_test)

### 모델 평가

In [49]:
# 필요한 함수 임포트
from sklearn.metrics import accuracy_score, classification_report

# 평가용 데이터에 대한 4가지 성능 측정
performance_stack = classification_report(y_test, pred_test_stack)

# 결과 확인
print(f'Stacking 분류 모델의 평가용 데이터에 대한 4가지 성능: \n{performance_stack}')

Stacking 분류 모델의 평가용 데이터에 대한 4가지 성능:
              precision    recall  f1-score   support

         0.0       0.77      0.73      0.75      7070
         1.0       0.74      0.78      0.76      7069

    accuracy                           0.75     14139
   macro avg       0.76      0.75      0.75     14139
weighted avg       0.76      0.75      0.75     14139