# 01. 데이터 전처리 — `pd.concat()` 실습
> 교재 26~28p · SK네트웍스 Family AI 캠프 37기 · 2026-10-14

`pd.concat()`은 여러 DataFrame을 **한 개의 DataFrame으로 병합**한다.

| 매개변수 | 의미 |
|---|---|
| `objs` | 합칠 DataFrame 리스트 `[df1, df2, df3]` |
| `axis=0` (기본값) | **공통 컬럼 기준, 행(y축) 방향**으로 아래에 이어 붙임 |
| `axis=1` | **공통 행 인덱스 기준, 열(x축) 방향**으로 옆에 이어 붙임 |
| `ignore_index=True` | 기존 인덱스를 버리고 0부터 새로 매김 |
| `join='outer'/'inner'` | 컬럼(또는 인덱스)이 다를 때 합집합/교집합 |

In [1]:
# 필요한 라이브러리 임포트
import pandas as pd

## 1. 실습용 DataFrame 3개 생성

In [2]:
# 컬럼(A~D)은 같고, 행 인덱스만 다른 DataFrame 3개
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

display(df1, df2, df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

## 2. `axis=0` — 행(y축) 방향 병합 (기본값)
공통된 컬럼을 기준으로 **아래로** 이어 붙인다.

In [3]:
# axis=0 방향으로 병합(기본값) + 인덱스 새로 매기기
df_concat = pd.concat([df1, df2, df3], ignore_index=True)

print(f'병합 결과 shape: {df_concat.shape}')   # (12, 4)
display(df_concat)

병합 결과 shape: (12, 4)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [4]:
# 비교: ignore_index=False(기본값)면 원래 인덱스를 그대로 유지
# -> 원본 인덱스가 겹치면 중복 인덱스가 생기므로 주의
display(pd.concat([df1, df2, df3]))

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

## 3. `axis=1` — 열(x축) 방향 병합
공통된 **행 인덱스**를 기준으로 **옆으로** 이어 붙인다. 인덱스가 다르면 빈칸은 `NaN`이 된다.

In [5]:
# df1(인덱스 0~3)과 df2(인덱스 4~7)는 겹치는 인덱스가 없음 -> NaN 다수 발생
df_concat_col = pd.concat([df1, df2], axis=1)
display(df_concat_col)

     A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5
6  NaN  NaN  NaN  NaN   A6   B6   C6   D6
7  NaN  NaN  NaN  NaN   A7   B7   C7   D7

In [6]:
# 인덱스를 맞춰서 옆으로 붙이는 실전 예: 같은 대상의 다른 특성 합치기
df_left = df1[['A', 'B']]
df_right = df1[['C', 'D']]

display(pd.concat([df_left, df_right], axis=1))

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

## 4. 컬럼이 다를 때 — `join` 옵션
- `join='outer'`(기본값): 모든 컬럼 유지, 없는 값은 `NaN`
- `join='inner'`: 공통 컬럼만 유지

In [7]:
# df4는 컬럼 B, D, F (A, C 없음 / F는 새 컬럼)
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                    'D': ['D2', 'D3', 'D6', 'D7'],
                    'F': ['F2', 'F3', 'F6', 'F7']},
                   index=[2, 3, 6, 7])

print('join="outer" (합집합)')
display(pd.concat([df1, df4], ignore_index=True))

print('join="inner" (교집합: B, D만 남음)')
display(pd.concat([df1, df4], join='inner', ignore_index=True))

join="outer" (합집합)

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
4  NaN  B2  NaN  D2   F2
5  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

join="inner" (교집합: B, D만 남음)

    B   D
0  B0  D0
1  B1  D1
2  B2  D2
3  B3  D3
4  B2  D2
5  B3  D3
6  B6  D6
7  B7  D7

## ✅ 정리
- `pd.concat([df1, df2, df3])` → 기본은 **행 방향(axis=0)** 병합
- 인덱스를 새로 매기려면 `ignore_index=True`
- `axis=1`은 **행 인덱스가 같아야** 의미 있는 병합이 된다
- 컬럼이 다를 땐 `join='inner'`로 공통 컬럼만 남길 수 있다